export const AUTHENTICATION_SCREEN = 'AUTHENTICATION_SCREEN';
export const RESET_PASSWORD_SCREEN = 'RESET_PASSWORD_SCREEN';
export const REGISTRATION_SCREEN = 'REGISTRATION_SCREEN';
export const FIRST_QUIZ_SCREEN = 'FIRST_QUIZ_SCREEN';
export const SECOND_QUIZ_SCREEN = 'SECOND_QUIZ_SCREEN';
export const QUIZ_DONE_SCREEN = 'QUIZ_DONE_SCREEN';
export const ALL_CONSULTATION_SCREEN = 'ALL_CONSULTATION_SCREEN';
export const CLIENT_CONSULTATION_SCREEN = 'CLIENT_CONSULTATION_SCREEN';
export const CONSULTATION_SCREEN = 'CONSULTATION_SCREEN';
export const RE_CHANGE_CONSULTATION_SCREEN = 'RE_CHANGE_CONSULTATION_SCREEN';

export const MAIN_SCREEN = 'MAIN_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';

export const MY_CLIENT_STACK = 'MY_CLIENT_STACK';
export const CLIENT_LIST_SCREEN = 'CLIENT_LIST_SCREEN';
export const CLIENT_SCREEN = 'CLIENT_SCREEN';
export const CHAT_SCREEN = 'CHAT_SCREEN';
export const CONS_CHAT_SCREEN = 'CONS_CHAT_SCREEN';
export const IMAGE_FULL_SCREEN = 'IMAGE_FULL_SCREEN';

export const PROFILE_STACK = 'PROFILE_STACK';

export const SECOND_QUIZ_STACK = 'SECOND_QUIZ_STACK';

export const ALL_CONSULTATION_STACK = 'ALL_CONSULTATION_STACK';
export const AUTHENTICATION_STACK = 'AUTHENTICATION_STACK';
export const MAIN_STACK = 'MAIN_STACK';
